---
- name: Evaluate user{{ item }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: 'user{{ item }}'
    state: present

- name: Evaluate Data Grid Operator Group
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'datagrid-operatorgroup.yaml.j2') }}"

- name: Evaluate Data Grid Subscription
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'datagrid-subscription.yaml.j2') }}"
