---
- name: "Get Che user{{ item }} token"
  uri:
    url: http://keycloak-{{ che_project }}.{{ route_subdomain }}/auth/realms/che/protocol/openid-connect/token
    method: POST
    body:
      username: user{{ item }}
      password: "{{ workshop_che_user_password }}"
      grant_type: "password"
      client_id: "admin-cli"
    body_format: form-urlencoded
    status_code: 200
  register: user_token

- name: Get workspace for user{{ item }}
  uri:
    url: "http://che-{{ che_project }}.{{ route_subdomain }}/api/workspace"
    method: GET
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200
  register: workspace_def

- name: Verify and start workspace for user{{ item }} again if stopped
  when: workspace_def.json[0].status == "STOPPED"
  uri:
    url: "http://che-{{ che_project }}.{{ route_subdomain }}/api/workspace/{{ workspace_def.json[0].id }}/runtime"
    method: POST
    headers:
      Accept: application/json
      Authorization: "Bearer {{ user_token.json.access_token }}"
    status_code: 200

